### PR TITLE
Up

### PR DESCRIPTION
**Pull request by kevinkoda**

### CODE REVIEW

**Comment by kevinkoda** [comment]
edited

**Comment by robman** [comment]
Hi @kevinkoda we won't accept this pull request as none of the changes I can see are actually improving or extending this code.

In fact in at least 2 places you have removed the reference to our authorship which is a breach under the open source license - please restore this attribution if you intend to keep using this code.

The other changes are adding things like your fixed ip address and port. This is obviously something each user should set and a fixed ip address shouldn't be included in this type of example code.

**Comment by kevinkoda** [comment]
Sorry new to github was just messing with code didn't intend to push.
Was only trying to change something on code (text was the easiest to edit) in branch to master.  But got it all wrong. If it happens again just ignore.  

Sorry Kevin. 

-----Original Message-----

**Comment by robman** [comment]
No problems @kevinkoda - now you know what that button does 8)

**Pull request closed without merging**
